name: CI

on:
  - pull_request
  - push

jobs:
  PHPUnit:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['7.4']

    name: PHPUnit - PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Run unit tests
        run: vendor/bin/codecept run
